Vagrant.configure("2") do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "CentOS-6.3-x86_64-reallyminimal"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "https://s3.amazonaws.com/1412126a-vagrant/CentOS-6.3-x86_64-reallyminimal.box"

  config.vm.network :public_network

  config.vm.define :master do |master|

    master.vm.hostname = "master.storm.nathan.gs"
    master.vm.provision :puppet do |puppet|
      puppet.manifests_path = "manifests/"
      puppet.manifest_file = "master.pp"

      #puppet.options = "--hiera_config hiera.yaml"
      puppet.module_path  = "modules"
      puppet.facter = {
          "is_vagrant" => true,
      }

    end
  end

  config.vm.define :worker do |worker|
    worker.vm.provision :puppet do |puppet|
      puppet.manifests_path = "manifests/"
      puppet.manifest_file = "worker.pp"

      #puppet.options = "--hiera_config hiera.yaml"
      puppet.module_path  = "modules"
      puppet.facter = {
          "is_vagrant" => true,
      }

    end
  end

end